# Site settings
title: CBM Campbelltown
email: contact@cbmcampbelltown.com
facebook: "facebook.com/groups/cbmcampbelltown"
instagram: https://www.instagram.com/cbmcampbelltown/
#parent: "www.mycbm.org.au"
description: > # this means to ignore newlines until "baseurl:"
  Uncover the real Jesus by reading the Bible with us!
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.cbmcampbelltown.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
github_username: cbmcampbelltown
